# Generated by Django 3.1.4 on 2021-04-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='name',
            field=models.CharField(default='22', max_length=100),
            preserve_default=False,
        ),
    ]
