# Generated by Django 3.1.4 on 2021-04-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='logo',
            field=models.CharField(default='fruit', max_length=10),
            preserve_default=False,
        ),
    ]
