# Generated by Django 3.1.4 on 2021-04-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('count', models.IntegerField(verbose_name='商品数目')),
                ('comment', models.TextField(verbose_name='评论')),
            ],
            options={
                'verbose_name': '订单商品表',
                'verbose_name_plural': '订单商品表',
                'db_table': 'df_order_goods',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单id')),
                ('pay_way', models.SmallIntegerField(choices=[(1, '货到付款'), (2, '支付宝'), (3, '微信付款'), (4, '银联付款')], default=2, verbose_name='支付方式')),
                ('count', models.IntegerField(verbose_name='商品总数')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '待评价'), (3, '待发货'), (4, '待收货'), (5, '已完成')], default=1, verbose_name='状态')),
                ('order_no', models.CharField(max_length=100, verbose_name='支付编号')),
            ],
            options={
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表',
                'db_table': 'df_order_info',
            },
        ),
    ]
